### ISSUE TITLE
Using async_lru with tenacity @retry decorator

### ISSUE THREAD

**Issue by anvth** [aio-libs/async_lru#158]
I have the following aiohttp app:

```
import asyncio
import aiohttp
from datetime import datetime

from async_lru import alru_cache
from aiocache.plugins import HitMissRatioPlugin
from aiohttp import web
from tenacity import (retry, retry_if_exception_type, stop_after_attempt, wait_exponential)
import random


@alru_cache(maxsize=1)
@retry(retry=retry_if_exception_type(Exception), stop=stop_after_attempt(5))
async def fetch(url):
    random.seed(int(datetime.now().timestamp()))
    rand_number = random.randint(1, 9)
    print(rand_number)
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            if rand_number % 2 == 0:
                print("attempt exception...")
                raise Exception
            
            print("attempt default...")
            await asyncio.sleep(1)
            return await response.text()


async def handle(request):
    print(f"fetching default")
    text = await fetch('http://google.com')
    print(fetch.cache_info())
    return web.Response(text=text)


app = web.Application()
app.add_routes([web.get('/', handle)])


web.run_app(app, port=8081)
```

But when I try to run this, I get the following:
```
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
Traceback (most recent call last):
  File "cache.py", line 13, in <module>
    @retry(retry=retry_if_exception_type(Exception), wait=wait_exponential(multiplier=0.2, max=3), stop=stop_after_attempt(5))
  File "/Users/anvith.shivakumara/Workspace/python-playgraound/async_lru.py", line 183, in wrapper
    'Coroutine function is required, got {}'.format(fn))
RuntimeError: Coroutine function is required, got <function fetch at 0x1114c41e0>
```
But looking at documentation for tenacity here, https://github.com/jd/tenacity#async-and-retry, there seems to be support for asyncio. Can someone help me get these two running together or at least help understand why I cannot?

Thank you.

**Comment by anvth** [comment]
Probably the right place to ask this is [here](https://groups.google.com/forum/#!topic/aio-libs/wJKLV1Mykb0). Hence, closing it.

**Comment by asvetlov** [comment]
`tenacity.retry()` returns an object that fails `iscoroutinefunction()` check.

Funny fact: `tenacity` uses this check itself too. The following code doesn't work
```
@tenacity.retry()
@tenacity.retry()
async def fetch():
   ...
```
